# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HyphenateDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Hyphenate'
  pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
#  pod 'RedpacketAliAuthLib', '~> 1.1.4'
#  pod 'RedpacketLib'
  #pod 'Hyphenate', '~> 3.3.7'
  #pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git', :tag => '3.3.7'
  #环信所用到
  #DACircularProgress
  #EaseUI
  #Hyphenate
  #MBProgressHUD
  #MJRefresh
  #MWPhotoBrowser
  #SDWebImage
  
  pod 'ReactiveObjC'
  pod 'AFNetworking'
  pod 'MJExtension'

  # Pods for HyphenateDemo

  target 'HyphenateDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HyphenateDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
